# Generated by Django 5.1.1 on 2025-01-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
